import type { Config } from 'tailwindcss'
import typography from '@tailwindcss/typography'
import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#d2d9f8',
        'on-error-container': '#782232',
        'outline-variant': '#abb3b7',
        'error-dim': '#4f0116',
        'primary-fixed': '#e2dfff',
        'tertiary-fixed-dim': '#c4cbe9',
        'surface-variant': '#dbe4e7',
        'secondary-container': '#dde1ff',
        'inverse-on-surface': '#9b9d9e',
        'on-tertiary': '#faf8ff',
        'on-error': '#fff7f7',
        'primary-container': '#e2dfff',
        'inverse-surface': '#0c0f10',
        'primary': '#4d44e3',
        'on-surface-variant': '#586064',
        'on-secondary-fixed-variant': '#555a74',
        'surface-container-low': '#f1f4f6',
        'surface-dim': '#d1dce0',
        'on-secondary': '#faf8ff',
        'on-tertiary-container': '#444c65',
        'tertiary-container': '#d2d9f8',
        'on-secondary-container': '#4c506a',
        'on-primary-fixed-variant': '#4a40e0',
        'surface-bright': '#f8f9fa',
        'primary-fixed-dim': '#d2d0ff',
        'outline': '#737c7f',
        'surface-container-highest': '#dbe4e7',
        'on-primary': '#faf6ff',
        'on-tertiary-fixed': '#323951',
        'secondary-fixed-dim': '#cfd3f2',
        'surface': '#f8f9fa',
        'background': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'tertiary': '#575e78',
        'secondary': '#595e78',
        'primary-dim': '#4034d7',
        'error-container': '#ff8b9a',
        'on-surface': '#2b3437',
        'surface-container-high': '#e3e9ec',
        'secondary-fixed': '#dde1ff',
        'inverse-primary': '#8582ff',
        'on-tertiary-fixed-variant': '#4e556f',
        'on-secondary-fixed': '#393e57',
        'on-primary-fixed': '#2a13c5',
        'secondary-dim': '#4d526b',
        'surface-tint': '#4d44e3',
        'surface-container': '#eaeff1',
        'error': '#9e3f4e',
        'on-primary-container': '#3f33d6',
        'on-background': '#2b3437',
        'tertiary-dim': '#4b526c',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [typography, forms, containerQueries],
}

export default config
